name: "EnOcean MQTT TCP/Serial"
version: "1.1.54"
slug: "enocean-mqtt-tcp"
description: "Advanced EnOcean to MQTT bridge with Web UI. Supports TCP & Serial Transceivers, zero config, and 152+ EEP profiles."
url: "https://github.com/tostmann/ha-enocean-mqtt-slim"
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
  - i386
init: false
uart: true
ingress: true
ingress_port: 8099
panel_icon: mdi:radio-tower
panel_title: "EnOcean TCP"
homeassistant_api: true
services:
  - mqtt:need
map:
  - config:rw
  - share:rw
  - ssl:ro

options:
  serial_device: null
  custom_address: ""
  log_level: "info"
  restore_state: true
  restore_delay: 5

schema:
  serial_device: "device(subsystem=tty)?"
  custom_address: "str?"
  log_level: "list(debug|info|warning|error)"
  restore_state: "bool"
  restore_delay: "int(1,60)"
