name: "EnOcean MQTT TCP/Serial"
version: "1.2.4"
slug: "enocean-mqtt-tcp"
description: "Advanced EnOcean Bridge. Select USB device OR enter TCP Address manually. Includes Auto-Provisioning."
url: "https://github.com/tostmann/ha-enocean-mqtt-slim"
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
  - i386
init: false
uart: true
ingress: true
ingress_port: 8099
panel_icon: mdi:radio-tower
panel_title: "EnOcean TCP"
homeassistant_api: true
services:
  - mqtt:need
map:
  - config:rw
  - share:rw
  - ssl:ro

options:
  serial_device: null
  tcp_address: ""
  log_level: "info"
  restore_state: true
  restore_delay: 5
  provisioning_url: "https://prov.busser.io"

schema:
  serial_device: "device(subsystem=tty)?"
  tcp_address: "str?"
  log_level: "list(debug|info|warning|error)"
  restore_state: "bool"
  restore_delay: "int(1,60)"
  provisioning_url: "str?"
